name: learn-github-actions
run-name: ${{github.actor}} is learning GitHub actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout the current repository on to the runner
      - uses: actions/setup-node@v3 # install node js, verions 14
        with:
          node-version: "14"
      - run: npm install -g bats # install bats - testing framework for bash.
      - run: bats -v # oupts installed version of bats
